export { default as StyledButton } from './StyledButton'
export { default as StyledPage } from './StyledPage'
export { default as StyledContainer } from './StyledContainer'
export { default as StyledTitle } from './StyledTitle'
export { default as StyledText } from './StyledText'
